---
- name: create log output directory
  file: path={{ httpd.log_output_dir }} state=directory owner={{ httpd.user }} group={{ httpd.group }} mode=0755

- name: install httpd
  yum: name=httpd state=installed

- name: copy default httpd.conf
  template: src=httpd.conf dest=/etc/httpd/conf/
  notify: restart httpd

- name: copy httpd-proxy.conf
  template: src=httpd-proxy.conf dest=/etc/httpd/conf.d/
  notify: restart httpd

- name: service
  service: name=httpd state=running enabled=yes

